name: Build IOS
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  hosting:
    name: Build Flutter App
    runs-on: macos-latest
    steps: 
    
    # checkout repository
    - uses: actions/checkout@v2
      
    # Install flutter command
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'          
        channel: 'stable'
          
    # Build flutter app
    - name: Build Flutter App
      run: |          
        flutter pub get
        flutter build apk
        flutter build ios --release --no-codesign
          
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-app
        path: build/app/outputs/apk/release/app-release.app
