name: Build IOS
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  hosting:
    name: Build Flutter App
    runs-on: macos-latest
    steps: 
    
    # checkout repository
    - uses: actions/checkout@v2
      
    # Install flutter command
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'          
        channel: 'stable'
          
    # Build flutter for ios
    - name: Build iOS App
      run: |
        flutter build ios --no-codesign
        cd build/ios/iphoneos
        mkdir Payload
        cd Payload
        ln -s ../Runner.app
        cd ..
        zip -r app.ipa Payload
          
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-app
        artifacts: 'build/ios/iphoneos/Runner.app,build/ios/iphoneos/app.ipa'
