name: Build apk
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    # This job will run on mac virtual machine
    runs-on: macos-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'
        channel: 'stable'
        
    - name: Build Flutter App    
      run: flutter pub get;flutter build apk
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
